controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.215
    wheel_radius: 0.0325

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: "base_link"
    
    linear:
      x:
        max_velocity: 0.2 # Maximal speed of turtlebot

position_controller:
  ros__parameters:
    joints:
      - arm_left_joint
      - arm_right_joint